In [1]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(arr1)
print("Dimensions:", arr1.ndim)

arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("\n2D Array:")
print(arr2)
print("Dimensions:", arr2.ndim)

arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("\n3D Array:")
print(arr3)
print("Dimensions:", arr3.ndim)

1D Array:
[10 20 30 40 50]
Dimensions: 1

2D Array:
[[10 20 30]
 [40 50 60]]
Dimensions: 2

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimensions: 3


In [4]:
import numpy as np
arr=np.array([2,3,7,5,6,4])
print("Original array",arr)
arr_n=arr.reshape(2,3)
print("after reshape..")
print(arr_n)

Original array [2 3 7 5 6 4]
after reshape..
[[2 3 7]
 [5 6 4]]


In [5]:
import numpy as np
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
#to convert two dimension array into single dimension with ravel function
arr_n=arr2.ravel()
print(arr_n)

[10 20 30 40 50 60]


In [17]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
a=np.split(arr,3)
print(a)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [18]:
import numpy as np
a=np.array([["coffee","cookie","pasta","Burger"],["juice","Sandwich","Pizza","Shake"]])
b=np.array([[7,10,20,50],[6,3,80,45]])
merged_vertical=np.vstack((a,b))
print(merged_vertical)

[['coffee' 'cookie' 'pasta' 'Burger']
 ['juice' 'Sandwich' 'Pizza' 'Shake']
 ['7' '10' '20' '50']
 ['6' '3' '80' '45']]


In [19]:
import numpy as np
a=np.array([["coffee","cookie","pasta","Burger"],["juice","Sandwich","Pizza","Shake"]])
b=np.array([[7,10,20,50],[6,3,80,45]])
merged_horizontal=np.hstack((a,b))
print(merged_horizontal)

[['coffee' 'cookie' 'pasta' 'Burger' '7' '10' '20' '50']
 ['juice' 'Sandwich' 'Pizza' 'Shake' '6' '3' '80' '45']]


In [20]:
import numpy as np

a = np.array([
    ["coffee", "cookie", "pasta", "Burger"],
    ["juice", "Sandwich", "Pizza", "Shake"]
])

b = np.array([
    [7, 10, 20, 50],
    [6, 3, 80, 45]
])

for row1, row2 in zip(a, b):
    merged = list(zip(row1, row2))
    print(merged)

[(np.str_('coffee'), np.int64(7)), (np.str_('cookie'), np.int64(10)), (np.str_('pasta'), np.int64(20)), (np.str_('Burger'), np.int64(50))]
[(np.str_('juice'), np.int64(6)), (np.str_('Sandwich'), np.int64(3)), (np.str_('Pizza'), np.int64(80)), (np.str_('Shake'), np.int64(45))]


In [21]:
import numpy as np

marks = np.array([78, 80, 60, 69, 50])

mean_marks = np.mean(marks)
print("Average marks:", mean_marks)

median_marks = np.median(marks)
print("Median marks:", median_marks)

minimum_marks = np.min(marks)
print("Minimum marks:", minimum_marks)

maximum_marks = np.max(marks)
print("Maximum marks:", maximum_marks)

Average marks: 67.4
Median marks: 69.0
Minimum marks: 50
Maximum marks: 80


In [22]:
import numpy as np
prices=np.array([
    [100,200,150],
    [120,220,180],
    [130,210,160]
])
print(prices)
mean_all=np.mean(prices)
print(mean_all)
mean_rows=np.mean(prices,axis=1)
print("Row wise Mean value ",mean_rows)
 
mean_column=np.mean(prices,axis=0)
print("Column wise Mean value ",mean_column)

[[100 200 150]
 [120 220 180]
 [130 210 160]]
163.33333333333334
Row wise Mean value  [150.         173.33333333 166.66666667]
Column wise Mean value  [116.66666667 210.         163.33333333]


In [23]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Product ",np.dot(a,b))

Product  32


In [24]:
import numpy as np
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [25]:
import numpy as np

a = np.linspace(0, 10, 5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [26]:
arr = np.array([80,40,90,60])
 
print(np.argsort(arr))

[1 3 0 2]


In [27]:
import numpy as np
data = np.array([

    [101, 500],

    [102, 700],

    [103, 900]

], dtype=float)
 data[:, 1] = data[:, 1] * 1.10
print(data)
 

[[101. 550.]
 [102. 770.]
 [103. 990.]]


In [28]:
import numpy as np
temperature_data=np.random.randint(20,45,size=(30,4))
print(temperature_data)
daily_avg=np.mean(temperature_data,axis=1)
print("Daily Average Temperature",daily_avg)
first_28_days=temperature_data[:28]
weekly_avg=np.mean(first_28_days.reshape(4,7,4),axis=(1,2))
print("weekly average based on first 4 full weeks):\n",weekly_avg)
 
hottest_day=np.argmax(daily_avg)
coldest_day=np.argmin(daily_avg)
print(f"Hottest day: Day{hottest_day+1} with {daily_avg[hottest_day]:.2f}C")
print(f"Coldest day: Day{coldest_day+1} with {daily_avg[coldest_day]:.2f}C")

[[30 26 25 20]
 [20 42 38 32]
 [44 33 44 42]
 [36 37 23 29]
 [34 27 44 38]
 [41 44 32 39]
 [32 32 25 27]
 [42 32 26 41]
 [42 27 40 31]
 [21 23 28 28]
 [24 33 20 23]
 [34 43 44 26]
 [21 44 38 40]
 [24 33 28 23]
 [30 41 36 30]
 [25 20 32 22]
 [33 24 25 44]
 [30 24 41 20]
 [39 34 40 26]
 [22 33 27 31]
 [41 27 37 44]
 [20 38 23 25]
 [42 41 28 44]
 [25 28 41 28]
 [35 29 37 38]
 [37 43 25 40]
 [39 40 22 31]
 [42 31 26 36]
 [43 25 23 34]
 [35 35 37 32]]
Daily Average Temperature [25.25 33.   40.75 31.25 35.75 39.   29.   35.25 35.   25.   25.   36.75
 35.75 27.   34.25 24.75 31.5  28.75 34.75 28.25 37.25 26.5  38.75 30.5
 34.75 36.25 33.   33.75 31.25 34.75]
weekly average based on first 4 full weeks):
 [33.42857143 31.39285714 31.35714286 33.35714286]
Hottest day: Day3 with 40.75C
Coldest day: Day16 with 24.75C


In [29]:
import numpy as np
# GPS coordinates of delivery rider (latitude, longitude)
lat = np.array([28.6139, 28.6145, 28.6152, 28.6158, 28.6164])
lon = np.array([77.2090, 77.2098, 77.2105, 77.2112, 77.2120])
# Calculate movement between consecutive locations
dlat = np.diff(lat)
dlon = np.diff(lon)
# Approximate distance in km
distance = np.sqrt(dlat**2 + dlon**2) * 111
# Total distance covered
total_distance = np.sum(distance)
print("Distance between each GPS update (km):")
print(np.round(distance, 3))
print("\nTotal Distance Travelled (km):")
print(round(total_distance, 3))

Distance between each GPS update (km):
[0.111 0.11  0.102 0.111]

Total Distance Travelled (km):
0.434


In [30]:
import numpy as np

crime_scene = np.array([12, 45, 78, 23, 56])

suspect1 = np.array([12, 45, 78, 20, 50])
suspect2 = np.array([10, 40, 70, 23, 56])
suspect3 = np.array([12, 45, 78, 23, 56])

match1 = np.sum(crime_scene == suspect1)
match2 = np.sum(crime_scene == suspect2)
match3 = np.sum(crime_scene == suspect3)

print("Suspect 1 Match:", match1)
print("Suspect 2 Match:", match2)
print("Suspect 3 Match:", match3)

Suspect 1 Match: 3
Suspect 2 Match: 2
Suspect 3 Match: 5


In [31]:
import numpy as np

suspects = np.array(["John", "Mike", "Alex", "David"])

evidence = np.array([
    [85, 90, 75, 80],
    [70, 65, 80, 85],
    [95, 92, 90, 94],
    [60, 75, 55, 70]
])

print("Evidence Matrix")
print(evidence)

total_score = np.sum(evidence, axis=1)

print("\nTotal Evidence Score")
for name, score in zip(suspects, total_score):
    print(name, ":", score)

main_suspect = suspects[np.argmax(total_score)]

print("\nMost Likely Criminal:", main_suspect)
print("Highest Score:", np.max(total_score))

Evidence Matrix
[[85 90 75 80]
 [70 65 80 85]
 [95 92 90 94]
 [60 75 55 70]]

Total Evidence Score
John : 330
Mike : 300
Alex : 371
David : 260

Most Likely Criminal: Alex
Highest Score: 371
